# Generated by Django 2.1.2 on 2018-10-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='quota',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
